### ISSUE TITLE
PHP Fatal Errors

### ISSUE THREAD

**Issue by kurtsalsa** [govCMS/audit-site#1]
@fiasco ,

I'm not able to get this running. I'm on an ubuntu vm, I've run the steps in the README, I've checked the alias and I'm getting these errors when I try and run:
    $ 

```
PHP Warning:  require(/path/to/audit-site/vendor/seanhamlin/site-audit/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /path/to/audit-site/vendor/seanhamlin/site-audit/bin/site-audit on line 13
PHP Stack trace:
PHP   1. {main}() /path/to/audit-site/vendor/seanhamlin/site-audit/bin/site-audit:0
PHP Fatal error:  require(): Failed opening required '/path/to/audit-site/vendor/seanhamlin/site-audit/bin/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /path/to/audit-site/vendor/seanhamlin/site-audit/bin/site-audit on line 13
PHP Stack trace:
PHP   1. {main}() /path/to/audit-site/vendor/seanhamlin/site-audit/bin/site-audit:0
```

**Comment by fiasco** [comment]
Hmm, I thought I fixed that - I'll check it out.

**Comment by fiasco** [comment]
Yeah I fixed it with this here: https://github.com/seanhamlin/site-audit/pull/35 but @seanhamlin hasn't committed it yet.

I'll update this repo to use my fork until he merges.

**Comment by fiasco** [comment]
I've just pushed a fix. Can you please try again?

**Comment by kurtsalsa** [comment]
@fiasco , now I get
    Warning: require(/Users/kurt/Documents/sites/doca_all/audit-site/vendor/seanhamlin/site-audit/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/kurt/Documents/sites/doca_all/audit-site/vendor/seanhamlin/site-audit/bin/site-audit on line 13

    Fatal error: require(): Failed opening required '/Users/kurt/Documents/sites/doca_all/audit-site/vendor/seanhamlin/site-audit/bin/../vendor/autoload.php' (include_path='.:') in /Users/kurt/Documents/sites/doca_all/audit-site/vendor/seanhamlin/site-audit/bin/site-audit on line 13

**Comment by fiasco** [comment]
Are you running it from the root?

```
$ ./vendor/bin/site-audit 
Console Tool

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help              Displays help for a command
  list              Lists commands
 audit
  audit:acsf        Audit all sites on a Site Factory instance
  audit:multisite   Audit sites in a multisite instance
  audit:site        Audit a Drupal site to ensure it meets best practice
 checks
  checks:list       Show all checks available.
 profile
  profile:generate  Create a profile of checks.
```

Did you run composer update? Or perhaps try reinstall fresh? The `site-audit` binary should look like this:

```
$ cat ./vendor/bin/site-audit
#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use SiteAudit\CommandDiscovery;
use Composer\Autoload\ClassLoader;
use Doctrine\Common\Annotations\AnnotationRegistry;


/**
 * @var ClassLoader $loader
 */
$loader = require 'vendor/autoload.php';
AnnotationRegistry::registerLoader([$loader, 'loadClass']);

$application = new Application();
$application->addCommands(CommandDiscovery::findCommands());
$application->run();
```

**Comment by seanhamlin** [comment]
i have now merged seanhamlin/site-audit#35 so hopefully this makes your life easier ;)

**Comment by kurtsalsa** [comment]
@fiasco , @seanhamlin , I'm getting new PHP Fatal errors. I'm on a new laptop, so I've just cloned the repo this morning. It starts to work, then I get this:

`
The following modules are not enabled: govcms_tweaks, acsf, acsf_duplication, acsf_openid, acsf_pingdom, acsf_theme, acsf_variables, acquia_spi.
The following modules are not disabled: update.
No blacklisted permissions in use.
CSS aggregation is not enabled.
JS aggregation is not enabled.
User registration is disabled.
PHP Fatal error:  Class '\SiteAudit\Check\Drush\ModulePermissions' not found in /my_data/tools/audit-site/vendor/seanhamlin/site-audit/src/Command/SiteAudit.php on line 154

Fatal error: Class '\SiteAudit\Check\Drush\ModulePermissions' not found in /my_data/tools/audit-site/vendor/seanhamlin/site-audit/src/Command/SiteAudit.php on line 154
`

**Comment by fiasco** [comment]
@kurtsalsa if you remove line 32 of `profile.yml` it should work. Looks like this needs to be removed as it is no longer a feature.

**Comment by seanhamlin** [comment]
Yeah, I can take a look at this repo today, and sort it out.

**Comment by kurtsalsa** [comment]
@seanhamlin , @fiasco , removing that from profile.yml fixed the issue, thx.

**Comment by seanhamlin** [comment]
Hey @kurtsalsa, please see the most recent commit bdad698aadb02d9e3e11c5d6659915cc72ebc824 - hopefully this has what you need

**Comment by fiasco** [comment]
Whoops, it was using my fork because Sean hadn't committed a mich needed fix - but its there now: https://github.com/govCMS/audit-site/blob/master/composer.json

Try pull and composer install again.

**Comment by seanhamlin** [comment]
Closing this old issue.
