### ISSUE TITLE
Add different modes to run as developer or GovCMS

### ISSUE THREAD

**Issue by rooby** [govCMS/audit-site#17]
This audit should run different checks if being run by a site builder than if run by GovCMS.

Some of the issues that come out of the report are things that the site builder cannot mitigate, so they should not be shown to those users.

I suggest a flag that can be set to run in different modes.

**Comment by tobybellwood** [comment]
This will be coming - keep your eyes out. The 2.x branch is currently under heavy development, and offers a much wider range of functionality.  Check out the Drutiny docs at https://drutiny.github.io/ - we'll be implementing a number of different profiles (and custom policies).
