### ISSUE TITLE
Setting the email address to go nowhere?

### ISSUE THREAD

**Issue by ellioseven** [govCMS/audit-site#20]
Upon running the report, I get:

```
User #1 Locked Down Failed 
It is important to lock down user #1 in Drupal, this user is special an ignores access control.
User #1 is not secure.
Email address 'nobody@example.com' is not set correctly.
Remediation
Change the username to be random, set the email address to go nowhere, set the password to something secure.
```

How can I set the email address "to go nowhere"? I have specified multiple combinations but have not been able to move past this.

**Comment by fiasco** [comment]
Which version are you using? 1.x or 2.x?

**Comment by ellioseven** [comment]
7.x-2.x

**Comment by fiasco** [comment]
ok cool, then according to [the profile](https://github.com/govCMS/audit-site/blob/7.x-2.x/Profiles/preflight.profile.yml#L13) the email address needs to be no_reply@govcms.gov.au
