### ISSUE TITLE
"Page Cache Control Max Age Failed" false positive

### ISSUE THREAD

**Issue by ellioseven** [govCMS/audit-site#21]
When running an audit, I get:

```
Page Cache Control Max Age Failed 
Ensure you page cache expiry is set to an optimal level for best performance.
Page cache max-age is not set above 300 seconds. Currently set to 0.
Remediation
Set the variable page_cache_maximum_age to be greater than 300.
```

However when running `drush vget page_cache_maximum_age` I get:

```
page_cache_maximum_age: 300
```

Is there something I am doing wrong here?

**Comment by fiasco** [comment]
Could you set it to `301`? I'm curious to know if its because of an `>` evaluation opposed to a `>=` operator.

**Comment by ellioseven** [comment]
```
drush vset page_cache_maximum_age 301
```
Still gives me:

![image](https://user-images.githubusercontent.com/4191120/38654423-992eb29c-3e52-11e8-8708-08bf367058d2.png)

**Comment by fiasco** [comment]
I found the bug! Sorry this took soo long but is now fixed in the latest dev of the drutiny/plugin-drupal-7 branch.
