### ISSUE TITLE
Make a phar please so i can use it in the new script

### ISSUE THREAD

**Issue by simesy** [govCMS/audit-site#38]
https://github.com/govCMS/scaffold-tooling/blob/master/scripts/tests/govcms-audit

**Comment by fubarhouse** [comment]
We can look at integrating this to some degree within CI - I know a couple of people have asked previously but the tricky problem is storage. We need somewhere readily available to keep a copy from a commit. Tagging this repo seems like it will be reasonably unlikely to happen often - and typically they only ship with tagged releases.

GitHub Actions doesn't support PHP either, but that could be an avenue.

Alternatively and more applicably in your case, here's a little script which will produce a phar file:
```
#!/bin/bash
  
composer global require clue/phar-composer

rm -rf audit-site || true
git clone git@github.com:govCMS/audit-site.git && cd audit-site
composer install && ~/.composer/vendor/bin/phar-composer build .

mv audit.phar /usr/local/bin/drutiny
chmod +x /usr/local/bin/drutiny

cd - && rm -rf audit-site
```

**Note** this script comes with no disclaimer, please read it carefully before executing it in an isolated environment. Also note that it is my opinion, but I am not personally in favor of `phar` files, but this at least bridges a gap of entry and usability for some.

**Comment by simesy** [comment]
The script is cool. Why are we not tagging this repo?

**Comment by fubarhouse** [comment]
It's simply a rather infrequent process... I'm working on creating `phar` files for the last two releases that haven't received them yet now.

Edit: Releases `7.x-3.x-beta1` & `7.x-3.x-beta2` now have `phar` files associated to their releases.

**Comment by simesy** [comment]
Oh sweet :D :D
